version: "3"
services:
 gancio-telegram-bot:
  build: .
  image: "gancio-telegram-bot"
  container_name: "gancio-telegram-bot"
  restart: "on-failure"
  volumes:
   - ./gancio_telegram_bot:/app/gancio_telegram_bot # source code
   - ./.env:/app/.env # .env file
   - ./assets:/app/assets # assets dir with images needed by the bot
   - ./database:/app/database # directory with the .db database used for caching
   - ./logfile.log:/app/logfile.log # file for logging